[package]
name = "dingir-exchange"
version = "0.1.0"
authors = [ "lispczz <mycinbrin@gmail.com>" ]
edition = "2021"

[dependencies]
actix-rt = "2.9.0"
actix-web = "4.0.0-beta.12"
actix-web-httpauth = "0.8.1"
anyhow = "1.0.79"
arrayref = "0.3.6"
bytes = "1.0.1"
chrono = { version = "0.4.33", features = [ "serde" ] }
config_rs = { package = "config", version = "0.13.3" }
const_format = "0.2.15"
crossbeam-channel = "0.5.0"
dotenv = "0.15.0"
fluidex-common = { git = "https://github.com/fluidex/common-rs", branch = "master", features = [ "kafka", "non-blocking-tracing", "rust-decimal-dingir-exchange" ] }
futures = "0.3.30"
futures-channel = "0.3.30"
futures-core = { version = "0.3.30", default-features = false }
futures-util = { version = "0.3.30", default-features = false }
hex = "0.4.3"
humantime = "2.1.0"
humantime-serde = "1.0.1"
hyper = "1.1.0"
itertools = "0.12.0"
jsonwebtoken = "9.2.0"
lazy_static = "1.4.0"
log = "0.4.14"
nix = { version = "0.27.1", features = ["process"] }
num_enum = "0.7.1"
# orchestra = { git = "https://github.com/gcomte/orchestra.git", branch = "master", features = [ "exchange" ] }
orchestra = { path = "../orchestra", features = ["exchange"]}
# paperclip = { git = "https://github.com/fluidex/paperclip.git", features = [ "actix", "chrono", "rust_decimal" ] }
paperclip = { version = "0.8.2", features = [ "chrono", "rust_decimal", "actix4" ] }
qstring = "0.7.2"
rand = "0.8.3"
serde = { version = "1.0.124", features = [ "derive" ] }
serde_json = "1.0.64"
sqlx = { version = "0.7.3", features = [ "runtime-tokio-rustls", "postgres", "chrono", "bigdecimal", "migrate", "rust_decimal" ] }
thiserror = "1.0.24"
tokio = { version = "1.35.1", features = [ "full" ] }
tonic = "0.10.2"
tracing = "0.1"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.17"
ttl_cache = "0.5.1"
uuid = { version = "1.6.1", features = [ "serde" ] }

[[bin]]
name = "restapi"
path = "src/bin/restapi.rs"

[[bin]]
name = "matchengine"
path = "src/bin/matchengine.rs"

[features]
windows_build = [ "fluidex-common/rdkafka-dynamic" ]
emit_state_diff = [ ]
default = [ "emit_state_diff" ]
#default = ["windows_build"]
#default = ["windows_build", "emit_state_diff"]
