debug: true
db_log: postgres://exchange:exchange_AA9944@127.0.0.1/exchange
db_history: postgres://exchange:exchange_AA9944@127.0.0.1/exchange
brokers: '127.0.0.1:9092'
keycloak_pubkey: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi/vPc+g1YLouniZwTjF/riTC4FwffZATfkqL8P8k3X1iku38wrFYujJen6wn4A1SSAfYT1Y+/jG/xIuTeugVEEwmkGICUvQiSTlll9R5FrtRiFrXjuso74omuqiooGUzVfxvoNo6mnPXVZm3zr58OKofy/iw2VQdVLrGiBcssn6owiPhlY1C+EDxqQnMyi/kvB4crI47Wps6djoSsyuAxkDNomah3d+uLydXC9ujMj0wtgEO3C3E3mOFcIVgJeH65si2B4J67xPAyy9jX2uUjqMZPHTRck1OgJl5qB63TBjzUcv1noxvAYJBZSZSS3QFCmbiLTTSxd/bMT2SB1tZQQIDAQAB\n-----END PUBLIC KEY-----"
keycloak_admin_role: 'matchengine-admin'
keycloak_deposit_admin_role: 'deposit-admin'
keycloak_withdrawal_admin_role: 'withdrawal-admin'
